### ISSUE TITLE
How do i build

### ISSUE THREAD

**Issue by kartoffelmozart** [spelunky-fyi/modlunky2#113]
So this is not really an issue, but i was not sure where to ask. I am really interested in memory reading, but i haven't found a good project done in python to look into. I would really like to be able to use your source code, play around with it, and build and run it, to get an idea of how everything works. So i downloaded your source code, and tried building with your "build-exe.py" file, but it gave me an exception FileNotFoundError from inside the subprocess library. Am i on a totally wrong track? Is there a guide somewhere, how to build the modlunky2.exe file from the source code? 

Kind regards and thank you for an awesome Spelunky 2 mod
Kart

**Comment by gmjosack** [comment]
Have you read the [development instructions in the README](https://github.com/spelunky-fyi/modlunky2#development)? 

You shouldn't need to run `build-exe.py` as that requires a lot of extra setup around rust and pyinstaller for the distribution. If you just want to test you can just run the python locally per the development instructions on the command line. It you be very inefficient to develop via building the exe as it's a slow process to build and pack everything up.

**Comment by kartoffelmozart** [comment]
Ha, i completely overlooked that part of the README. Thank you!

**Comment by gmjosack** [comment]
No problem. Lemme know if you have any issues getting it running.

**Comment by kartoffelmozart** [comment]
Hey Gary. I have to admit that I didn't actually install modlunky2 before
downloading the source code :) I have now come as far as extracting
spel2.exe from the modlunky interface. It doesn't complete this task,
before raising a MemoryError. What now?

Den søn. 27. jun. 2021 kl. 18.30 skrev gary ***@***.***>:

**Comment by gmjosack** [comment]
You shouldn't need to extract the spel2.exe unless you want access to the assets. it's not necessary for the memory readers which are part of the trackers tab. If you're getting a `MemoryError` though it's likely you're running a 32 bit python. You should make sure you're running a 64 bit version of python.

If you have discord the various spelunky-fyi devs hang out in the `#s2-tooling` channel in the [Spelunky Community Server](https://discord.gg/spelunky-community)
