### ISSUE TITLE
Trackers: Don't reinitialize category tracker during ending cutscene

### ISSUE THREAD

**Issue by gmjosack** [spelunky-fyi/modlunky2#126]
Currently the tracker will re-initialize during the ending. I believe this is because the timer zeros out. Make the re-init smarter about which scene it's in so it only re-inits if the scene is in a level/camp.

**Comment by mauvealerts** [comment]
It turns out the timer remains frozen. The problem is the world+level are set to 1-1, presumably because the celebration takes place on the moon's surface (like the opening and camp). So, the tracker decides it's too early to show modifiers.

This doesn't happen when completing the Cosmic Ocean.

**Comment by mauvealerts** [comment]
Spencer mentioned Sunken City% switching to Any% on score screen. That happens because we check `self.world >= 7` and the world is now 1. To cover this, we can check the win state.
