### ISSUE TITLE
game not opening

### ISSUE THREAD

**Issue by Boggy23** [spelunky-fyi/modlunky2#165]
When i try to open the launcher, it immediately closes and sometimes another window ops up but i cant read it. anyone know what the problem is?

**Comment by gmjosack** [comment]
Window might be off the screen for some reason. I recommend trying to open `%localappdata%\spelunky.fyi\modlunky2` and removing `config.json`. If that doesn't work, I'd try removing the `Cache` directory, and lastly restarting your computer.

**Comment by Boggy23** [comment]
![2021-09-12](https://user-images.githubusercontent.com/90582987/133009889-4a02f60e-06d8-47aa-8201-01d4d21a4cbf.png)
this pops up every now and then. do you know what it means?
