### ISSUE TITLE
Can't extract. Spel2.exe is a patched exe. But it's not!

### ISSUE THREAD

**Issue by HiiamMarvin** [spelunky-fyi/modlunky2#170]
I use playlunky with one Lemon texture from mode\pack folder, it works great, then i used overlunky, and it also works great, next day i smashed button play and..i cannot sturtup playlunky its trowing me on desktop with message: 
" You're using Playlunky against a patched exe. For best results use Playlunky on a vanilla exe."  
I clean up all cache with the button on th main screen, "Clear cache" and tried to extract files again but it is impossible, i cant extract game assets it says:
 "Spel2.exe is a patched exe. Can't extract" 
But its not patched. Reinstalling the game from steam, veryfing files doesnt help, i see same error. I also tried to remove all stuff from appdata/local and tried to do all clean install even restarted my pc hopeless. How can i play my Tina without hat mode?))

**Comment by gmjosack** [comment]
Things are broken because of the new release that came out today. Will be pushing a fix soon but loading mods will be broken for a bit still. Going to take a bit to fix everything.

**Comment by HiiamMarvin** [comment]
> Things are broken because of the new release that came out today. Will be pushing a fix soon but loading mods will be broken for a bit still. Going to take a bit to fix everything.

Wow, that was fast. Okay, i just thought that you need to know about this, thx for your work man!
