### ISSUE TITLE
ModLunky 2 won't open at all

### ISSUE THREAD

**Issue by DumbassLink** [spelunky-fyi/modlunky2#172]
Ever since update 9.2v for Spelunky 2, Modlunky hasn't been working when I try to open Spelunky 2 with my mods. all that happens is a tab with code(I believe) pops up a Black screen appears, then back to the Modlunky tab.

pls help
![Screenshot (349)](https://user-images.githubusercontent.com/91152705/134223960-c341625d-61f5-462d-b901-8627156f0f80.png)

**Comment by gmjosack** [comment]
Modding is currently broken due to the 1.23.x release. We're working on it but it'll take some time.

**Comment by DumbassLink** [comment]
Thank you for notifying me quickly. I'm excited for when Modlunky is ready again and thank you for making mod Spelunky 2 easy.
