### ISSUE TITLE
Error: Failed finding pattern

### ISSUE THREAD

**Issue by PanzerZeiga** [spelunky-fyi/modlunky2#227]
Spelunky version: 1.25.2
Supported version: 1.25.0b
Error says it's an unknown version of Spelunky
![failed finding pattern](https://user-images.githubusercontent.com/98124355/150416532-3e875598-3a11-44db-8bae-d8fb7f48868d.PNG)

**Comment by mauvealerts** [comment]
Spelunky 2 version 1.25.2 was released yesterday and Playlunky requires
changes for each version. Folks are working on fixing it.
