### ISSUE TITLE
Add support for the whole ASCII/CP-1252 character set in tile codes

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/modlunky2#34]
Level files seem to support the whole one-byte https://en.wikipedia.org/wiki/Windows-1252 character set after quick testing, if you just save the file in the proper encoding. Add support for all the visible characters in the character set.

**Comment by Nobledez** [comment]
Done (closable)

**Comment by Dregu** [comment]
Not closable, apparently files with extended ascii are saved as utf-8, which totally doesn't work in the game.

**Comment by gmjosack** [comment]
This was completed recently (after the great utf-8 debacle)
