### ISSUE TITLE
No longer able to play online

### ISSUE THREAD

**Issue by seresharp** [spelunky-fyi/modlunky2#35]
Since the latest game update, attempting to enter online while modded will kick you back to the main menu after the "walls are shifting" screen. It makes sense to prevent online with unmodded randoms but it sucks not being able to play mods with friends anymore.

**Comment by gmjosack** [comment]
Did you re-extract from the clean update to make sure your running the mods on the latest version? You can confirm the version when you start the game and make sure it's 1.20.1c

**Comment by seresharp** [comment]
No, we had only re-packed the old version. It still works when updating correctly. Thank you for the fast response and sorry for the dumb mistake.

**Comment by gmjosack** [comment]
No worries. thanks for reporting back that it's working!
