### ISSUE TITLE
This version of Spelunky 2 is not supported by playlunky

### ISSUE THREAD

**Issue by gillisllc** [spelunky-fyi/modlunky2#396]
For the last few days when i launch Playlunky  using Modlunky 2 I get the following error:

This version of Spelunky 2 is not supported by playlunky, please update you game or check if there is a new version of Playlunky Available.   

Spelunky Version: could not be verified
Supported Version 1.25.2

Press OK to start without Playlunky or Cancel to yolo

If you press Cancel it does not load any mods but the game plays and loads from the steam install:

Mods in use:
Co-op shared Camera

I think this has to do with the Spelunky 2 August Patch? 

Is there anything that can be done?  My wife and her sister have 900+ hours into the game and play it everyday... but will not play without this mod.  I am hoping to fix it soon for them to play.

Thanks all.

**Comment by mauvealerts** [comment]
Folks are working on it. Since mods aren't officially supported, we rely on a ton of reverse engineering done on a volunteer basis. We don't have an ETA or anything.

**Comment by mauvealerts** [comment]
Playlunky Nightly now works with 1.27. You might need to hit the "Update Releases" button (rightmost column)
