### ISSUE TITLE
Executing Playlunky launcher with stable\Playlunky launcher . exe

### ISSUE THREAD

**Issue by hanno13** [spelunky-fyi/modlunky2#398]
hello.
When i try do Play with Playlunky in stable version or any other version it says: Executing Playlunky launcher with stable\Playlunky launcher . exe
and doesnt start.
What can i do?

**Comment by gmjosack** [comment]
A stable for 1.27 hasn't yet been released as it's only started working today so we'll be working out issues as reported on nightly before releasing a new stable

**Comment by hanno13** [comment]
Thanks so much! i I thought my Version doesnt work ever again.
Thanks again!

**Comment by mauvealerts** [comment]
Playlunky stable supports 1.27 these days (in addition to nightly)
