### ISSUE TITLE
Names are messed up in character select

### ISSUE THREAD

**Issue by Rapid-14** [spelunky-fyi/modlunky2#448]
The names are bugged and all the characters have the wrong names without and with mods. All the names start two characters further than normal. In order Ana is Colin, Margaret is Roffy, Colin is Alto, Roffy is Liz etc until it gets to Guy who is Ali and Classic Guy who is Bob. The last two are probably hired hand names.
![image](https://user-images.githubusercontent.com/117795009/200732470-060092a9-19b4-47ba-a700-cd9d9e065c88.png)

![image](https://user-images.githubusercontent.com/117795009/200732358-7cbb4a0b-57c8-4a33-8269-47a0f28aa18b.png)

**Comment by Rapid-14** [comment]
All with no mods

**Comment by gmjosack** [comment]
Clear your cache in the Playlunky tab

**Comment by Rapid-14** [comment]
Ok

**Comment by gmjosack** [comment]
This happens between game updates when they change the strings. If you see this you can always try clearing cache first but this is a common issue from the last update.

**Comment by Rapid-14** [comment]
how do I clear the cache?

**Comment by gmjosack** [comment]
![image](https://user-images.githubusercontent.com/231118/200732999-3746531c-72fd-43a0-8a76-f6e74658b822.png)

**Comment by Rapid-14** [comment]
I sure am blind thanks

**Comment by Rapid-14** [comment]
Yup That worked thanks!
