### ISSUE TITLE
Idea dump 

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/modlunky2#5]
I'll just dump some ideas here so I don't forget I had them.

  - Add a tab to the UI where you can backup and restore the exe or save with a single click, either from Mods/Extracted or through Steam, which you can trigger by running `steam://validate/418530`
  - Patch the game version string used for logging when repacking to be nice to the devs
```
Change
00 50 72 6F 64 75 63 74 69 6F 6E 00   " Production "
to
00 4D 6F 64 6C 75 6E 6B 79 32 00 00   " Modlunky2  "
and get
Spelunky 2 v1.19.0a(Modlunky2-64bits) boot-up: 12/07/20 08:20:38
```

**Comment by gmjosack** [comment]
Both of these are now implemented on `main` and will be in the next release. Thanks for the idea around release tagging.
