### ISSUE TITLE
A friend downloaded the Modlunky2.exe and got an error message

### ISSUE THREAD

**Issue by petersvp** [spelunky-fyi/modlunky2#53]
---------------------------
Fatal error detected
---------------------------
Failed to execute script pyinstaller-cli

---------------------------
OK   
---------------------------

**Comment by petersvp** [comment]
We had to MANUALLY extract the resources from a clean installation of Spelunky 2. Looks like vanilla, Modlunky2 isnt working now! This is a big in Overlunky. to repro, clean your Spelunky, start over fresh and the GUI wont pop

**Comment by gmjosack** [comment]
This should be fixed in the latest version. Thanks for the report!
