### ISSUE TITLE
Level Editor will not load generic.lvl - repro steps included with generic.lvl and mentioned mod

### ISSUE THREAD

**Issue by Artdigy** [spelunky-fyi/modlunky2#67]
So, I made about four new altar variation rooms and saved it. Immediately after trying to run level 1-1, the game crashes saying that there was a line size error on line 526. This was one of my custom rooms I had made for myself. It is marked as rare, and it has a backlayer. 

It is important to note that I am running _Bray's Map Gen Overhaul_, which can be found [here.](https://spelunky.fyi/mods/m/brays-map-gen-overhaul/)
It is a large mod that adds a lot of new rooms. I added four more additional rooms to the Kali Altar section of generic.lvl from this pack. 

**Repro Steps**
1. Download the mod and install it. You can choose to do this as an override, or as a pack.
2. Go to the level editor, and load levels from Overhaul's folder. Observe generic.lvl, and that it is functioning normally.
3. Replace generic.lvl with the zip provided at the bottom of this post. It contains my saved edits.
4. Your level editor should now be unable to load generic.lvl, giving this error in Modlunky's console.
`2021-03-15 03:08:17,605: Unhandled Exception: Traceback (most recent call last):
  File "tkinter__init.py", line 1883, in call__
  File "modlunky2\ui\levels.py", line 854, in tree_filesitemclick
 File "modlunky2\ui\levels.py", line 2347, in read_lvl_file
  File "modlunky2\levels\level_file.py", line 72, in from_path
 File "modlunky2\levels\tile_codes.py", line 285, in parse
ValueError: not enough values to unpack (expected 2, got 1)`
4.5 In the event that it does not, know that the file could be interpreted fine until Spelunky tried to load it and crashed. It no longer works.
5. Removing the lines in question that are "erroneous" will not fix the file and help it load. If you're having trouble reproducing it still, open another window and compare the differences of generic.lvl with the modified one if you could. Only shops and altar rooms have been modified. Nothing else. 

This is all. It appears that the .py files mentioned in the error are compiled within the .exe of modlunky, so I do not have access to them and cannot provide them.

Below is the generic.lvl file that I modified, with the attached codes for the rooms.  
[Generic.ZIP](https://github.com/spelunky-fyi/modlunky2/files/6139455/Generic.ZIP)

**Comment by Artdigy** [comment]
I am aware I have missing tiles for my sunken altar and the backlayer to Kali's Blessing, but I am generally confused as to why the editor will no longer load generic.lvl after spelunky loaded it once. Any attention on this would be appreciated

**Comment by Artdigy** [comment]
This has been fixed with the help of Gary. This had two errors caused by the level editor that resulted in the provided error.

1. \?crushtraplarge%95%upsidedown_spikesQ on line 78. Editor did this on its own, likely because it exceeded the expected padding size.
2. sleeping_hiredhand%40 had no provided symbol. This could have been caused by an excessive amount of tiles in the pallete, or it could have been caused for unknown reasons. These two in conjunction caused the error, and both had to be fixed.

The room size error is unknown as what is causing it, but Bray-G mentioned on line 2 of my Sunken Altar and the backlayer to Kali's Blessing, there are 9 tiles instead of the needed 10. I am not sure what he means by this.

**Comment by gmjosack** [comment]
The latest release fixed a lot of issues related to this. Please re-open if you see any reoccurrence.

Thanks for the super detailed issue!
