### ISSUE TITLE
Missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/modlunky2#70]
Can't run the new version on windows 7
![image](https://user-images.githubusercontent.com/36127424/112550123-2c833b80-8dbf-11eb-82a4-cc980ffc7e65.png)

**Comment by gmjosack** [comment]
I believe this might be related to upgrading to a recent version of Python as Windows 7 has been end of life for over a year and is no longer a supported operating system :(

**Comment by gmjosack** [comment]
Can you try the latest release now and see if it's fixed?

**Comment by Mr-Auto** [comment]
It's working now, thx
