### ISSUE TITLE
Cant Launch

### ISSUE THREAD

**Issue by BlasticBag** [spelunky-fyi/modlunky2#88]
When I try to open modlunky2 this message appears
![Capture](https://user-images.githubusercontent.com/83137921/115970214-fe546100-a50e-11eb-83c1-aefe7bbdf515.PNG)
.

**Comment by gmjosack** [comment]
Can you confirm which version you're trying to run?

I've not seen anyone report this before. My best guess would be that you don't have access to write to `C:\Users\%USERNAME%\AppData\Local` which is where a lot of caching and config gets written to

Can you check in `C:\Users\%USERNAME%\AppData\Local\spelunky.fyi\modlunky2` do you if anything exists there?

**Comment by BlasticBag** [comment]
I tried that but there is no spelunky.fyi file/folder

**Comment by gmjosack** [comment]
Are you able to create a folder in that directory?
