### ISSUE TITLE
Modlunky2 Marked "Neshta.Virus.FileInfector.DDS" by MalwareBytes

### ISSUE THREAD

**Issue by Rbmukthegreat** [spelunky-fyi/modlunky2#897]
Only happened with the most recent update. My friend also has malwarebytes and has reported the same issue.

**Comment by mauvealerts** [comment]
There isn't much we can do about false detections. If you're still getting it, you can try [reporting it](https://support.malwarebytes.com/hc/en-us/articles/360038524154-Report-a-false-positive-to-Malwarebytes-Support).
